version: 0.0
os: linux
files:
  - source: "/"
    destination: "/home/ec2-user/nextjs-app"
hooks:
  BeforeInstall:
    - location: before_install.sh 
      timeout: 300
      runas: root
  ApplicationStart:
    - location: app_start.sh 
      timeout: 600
      runas: root