version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo installing node packages
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo doing nothing
artifacts:
  files:
    - "**/*"
  discard-paths: yes